### ISSUE TITLE
HL!UL!SL isn't working on latest build of HL

### ISSUE THREAD

**Issue by Srandista** [rfinnie/hlulsl#7]
I tried HL!UL!SL on several machines, but same issue occur on every one of them. I can load mod and I can see HL: Uplink logo in corner, but when I try to actually run the new game, HL immediately crash without any error message. I'm attaching dump file created after HL crash.

[crash_hl.exe_dump.zip](https://github.com/rfinnie/hlulsl/files/3707678/crash_hl.exe_dump.zip)

**Comment by Srandista** [comment]
I can confirm, that there's definitely issue with latest version of HL, since when I tried HL!UL!SL on GoldSrc Package (linked below) with older build of HL, Uplink runs without any issues.

https://forums.sourceruns.org/t/goldsrc-package-2-3/2634

**Comment by rfinnie** [comment]
After a lot of trial and error, it looks like liblist.gam no longer likes explicit relative paths (../valve/dlls/hl.dll), and instead wants an implicit relative path (dlls/hl.dll)... even though that doesn't exist, it presumably overlays valve/ when it doesn't exist.

Anyway, 2.1 released.  Thanks for reporting!
