### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by PolarDawn** [rfinnie/hlulsl#8]
Chrome is giving a "Virus Detected" warning, preventing the game from downloading without overring the AV settings.

**Comment by Vallegames** [comment]
I had the same issues except I was using firefox and I actually downloaded the file before my antivirus told me it was a virus. I didn't execute the file so I'm really hoping it didn't do anything to my system.

**Comment by rfinnie** [comment]
Thanks for reporting.  It's a false positive; there is no virus, but not much can be done about it. I've updated https://www.halflifeuplink.com/hlulsl/ with an explanation of why.
